### ISSUE TITLE
Release new version to nextcloud 15 compatible

### ISSUE THREAD

**Issue by johnwmail** [icewind1991/group_everyone#4]
https://help.nextcloud.com/t/group-everyone-not-available-for-nc-15-0-0/43171

Any plan to release new version?
Thanks.

**Comment by JochenHWezel** [comment]
seems that appInfo.xml just became an update from
```
<nextcloud min-version="14" max-version="14" />
```
to
```
<nextcloud min-version="14" max-version="15" />
```
but kept at 
```
<version>0.1.0</version>
```

Maybe it's just time to release a 0.1.1 to get the build chain running? (I really don't know, but without reading any documentation on it, I could imagine the app market of nextcloud works that way) Or is there any other common todo for publishing the current files?

**Comment by fwolfst** [comment]
@JochenHWezel  Did you try that workaround locally? Or anybody else?

**Comment by jochenwezel** [comment]
Yes, I did it locally. 

If I remember correctly: the market place for apps just knows the 0.1.0 with appInfo version of an older patch level with <nextcloud min-version="14" max-version="14" /> 
I assume because there is no newer version available, it doesn't look/pull for an updated appInfo file and that's why the market place logic doesn't realize, that your app is already with support up to v15 (your patch was published AFTER the appInfo with v0.1.0 was published).

That's why I'd recommend to update the version here to 0.1.1 ;-)

**Comment by MorrisJobke** [comment]
@icewind1991 Mind to release a 15 version of the app?

**Comment by icewind1991** [comment]
released a 15 compatible version
